AllCops:
  Exclude:
    - spec/dummy_*/**/*
    - spec/dummy-*/**/*
  TargetRubyVersion: 2.5

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/spec_helper.rb

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*

Style/ClassVars:
  Exclude:
    # rubocop doesn't seem to know what's going on here.
    - lib/rails_drivers/extensions.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/*.rake

Style/MixinUsage:
  Exclude:
    - lib/tasks/*.rake

Metrics/AbcSize:
  Exclude:
    - lib/generators/**/*

Metrics/LineLength:
  Max: 130
